db/migrate/20150824230118_add_item_id_to_order_items.rb
db/schema.rb

Remove duplicate migration file

fix errant migration

---

Gemfile
spec/rails_helper.rb
spec/spec_helper.rb

removed comments in the Gemfile, spec_helper and rails_helper.

remove rails generated comments

---

app/assets/stylesheets/projects_index.css.scss
app/controllers/projects_controller.rb
app/views/projects/index.html.erb
db/schema.rb
spec/features/user_can_view_projects_spec.rb

Show all projects on site, regardless of company affiliation
Build out CSS
Hook up forms to connect to show
TODO:
add in method to dynamically adjust status bar

Build out projects index

---

Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/views/projects/index.html.erb

add bootstrap paginate gem
add paginate method in projects controller, action #index
add pagination bar in index.html.erb

add pagination for project index page

---

app/views/homepage/index.html.erb
spec/features/user_visits_home_page_spec.rb

User visits home page and views links - links included: Login, SignUp, About, Contact, and Featured Project

---

spec/features/visitor_can_view_a_companys_projects_spec.rb

Write a better feature test to show that accssing projects via companies only shows that company's projets

Improve feature test for multitenancy

---

app/views/layouts/_navigation_bar.html.erb
spec/features/user_registers_and_logout_spec.rb
spec/features/user_registers_spec.rb

User can successfully register and logout

---

app/assets/stylesheets/flash.css.scss
app/assets/stylesheets/forms.css.scss
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/views/layouts/_login_modals.html.erb
app/views/layouts/_navigation_bar.html.erb
app/views/layouts/_register_login_modals.html.erb
app/views/layouts/application.html.erb
spec/features/guest_user_visits_single_project_spec.rb
spec/features/user_visits_home_page_spec.rb
spec/features/visitor_can_log_in_spec.rb

User register/login flash messages up and working!!!! I'm so cool, it's crazy how cool I am today!
User can log in via modal
Appropriate flash is displayed depending on login success or failure
Feature tests
closes #42

User can successfully log in

---

app/controllers/orders_controller.rb
app/controllers/users_controller.rb
app/models/cart.rb
app/models/order.rb
app/models/order_item.rb
app/views/cart_items/index.html.erb
app/views/orders/index.html.erb
app/views/orders/show.html.erb
config/routes.rb
db/migrate/20150827201531_add_references_to_order_items.rb
db/migrate/20150827202811_change_quantity_to_funding_amount_in_order_items.rb
db/schema.rb
spec/fabricators/user_fabricator.rb
spec/features/user_funds_projects_spec.rb
spec/features/visitor_can_log_in_spec.rb
spec/models/cart_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

closes #6 
closes #37 
- user needs to log in to check out 
- user is redirected to their orders page on checkout 
NOTE: 
migrate - I added project_id and company_id to the order_items table.

37 user checks out

---

app/views/homepage/index.html.erb
app/views/layouts/_navigation_bar.html.erb
spec/features/registered_user_adds_projects_to_cart_spec.rb
spec/features/user_funds_projects_spec.rb
spec/features/user_visits_home_page_spec.rb

finished styling icons
and fixing tests

Style time

---

Gemfile
Gemfile.lock
app/controllers/users_controller.rb
app/views/layouts/_navigation_bar.html.erb
app/views/layouts/_register_login_modals.html.erb
app/views/layouts/_update_modals.html.erb
config/routes.rb
spec/features/registered_user_updates_info_spec.rb

Registered user updates account info

---

app/controllers/application_controller.rb
app/models/company.rb
app/models/user.rb
app/views/companies/projects/index.html.erb
app/views/layouts/_navigation_bar.html.erb
config/routes.rb
db/migrate/20150829200622_add_company_id_to_users.rb
db/schema.rb
spec/fabricators/user_fabricator.rb
spec/features/company_admin_views_projects_spec.rb
spec/models/user_spec.rb

closes #12 
- a company admin can view all the company's projects
- in the project view there is a link for "edit" and "delete" for each project 
- a regular user cannot view the "edit" and "delete" links for each project 
- add feature test
- add user model tests
TODO: 
fix the ugly conditional in the company/projects/index.html.erb view

12 bs admin views all projects

---

app/controllers/companies/projects_controller.rb
app/services/permission_service.rb
app/views/companies/projects/index.html.erb
app/views/companies/projects/show.html.erb
config/routes.rb
spec/features/company_admin_creates_project_spec.rb
spec/features/company_admin_deletes_project_spec.rb

Company admin can delete a project
Company admin can only delete projects for their company
Controller refactoring to use currently present permissions service

Company admin can delete a project

---

app/controllers/companies/projects_controller.rb
app/services/permission_service.rb
app/views/companies/projects/edit.html.erb
app/views/companies/projects/index.html.erb
spec/features/company_admin_can_edit_projects_spec.rb
spec/models/permission_service_spec.rb

Company admin can edit company's projects
Company admin can only edit the projects that belong to his/her company
More model tests for permissions service
closes #13

Company admin can edit projects

---

app/models/user.rb
db/seeds.rb

Create users
Create admins
Create roles
Update naming and descriptions of projects
Update email validation to be less restrictive
closes #53

Improve Seed File

---

app/controllers/companies/companies_controller.rb
app/views/companies/companies/dashboard.html.erb

- remove comment in companies/companies controller
- use helper method current_company in dashboard view

remove comment and use helper method

---

app/assets/javascript/application.js
app/assets/stylesheets/application.css.scss
app/controllers/cart_items_controller.rb
app/views/cart_items/index.html.erb
app/views/layouts/_navigation_bar.html.erb
spec/features/user_can_log_out_spec.rb
spec/features/user_cannot_visit_empty_cart_spec.rb
spec/rails_helper.rb

Empty cart #71

---

app/controllers/companies/projects_controller.rb
app/views/companies/companies/dashboard.html.erb
app/views/companies/projects/index.html.erb
app/views/companies/projects/show.html.erb
app/views/projects/index.html.erb
app/views/projects/show.html.erb
spec/features/company_admin_deletes_project_spec.rb

- fix broken button "company-name's dashboard" in projects#show and companies/projects#show
- add tests for company admin deleting projects
- remove "remove" link in the projects table on the admin dashboard because it was very cluttery

Fix broken buttons

---

spec/models/order_item_spec.rb
spec/models/order_spec.rb
spec/models/role_spec.rb
spec/models/user_role_spec.rb

Clean up and edit the remaining commented out tests so that they pass. Add additional coverage where warranted.

Clean up commented out tests

---

app/assets/javascript/scroll_page.js
app/assets/stylesheets/cart_page.css.scss
app/assets/stylesheets/custom.css.scss
app/assets/stylesheets/homepage-custom.css.scss
app/assets/stylesheets/nav_bar.css.scss
app/assets/stylesheets/order_accordion.css.scss
app/controllers/orders_controller.rb
app/helpers/application_helper.rb
app/views/cart_items/index.html.erb
app/views/layouts/_update_modals.html.erb
app/views/orders/index.html.erb
spec/features/user_funds_projects_spec.rb
spec/rails_helper.rb

Style hammer time

---

db/seeds.rb

robohash went down so changing image generation in seed file so that our site still looks professional

change project image generation

---

app/controllers/companies/users_controller.rb
app/views/layouts/application.html.erb

sanitize HTML in flash messages
Add flash when admin tries to add non-existent user as a collaborator

Sanitize Flash Messages

---

app/controllers/application_controller.rb
app/controllers/companies/companies_controller.rb
app/controllers/companies/projects_controller.rb
app/controllers/companies/users_controller.rb
app/controllers/orders_controller.rb
app/models/cart.rb
app/models/user.rb

Refactoring based on technical review
Clean up remaining permissions

Fix items from check in
